apiVersion: v1
kind: Service
metadata:
  name: welcome-service
spec:
  type: NodePort
  selector:
    app: welcome-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
      nodePort: 30080
